#!/usr/bin/env bash
# prints message infinity and beyond for
# eternity unless killed, not so ethernal after all :)

# Handle SIGTERM
trap "echo 'I am invincible!!!'" 15


# print the message
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
